#!/usr/bin/env node
/**
 * EQ design-tokens build.
 *
 * Reads JSON source under tokens/base/ and tokens/tiers/ and emits four
 * artefacts at the repo root:
 *
 *   tokens.css           - CSS custom properties + Tailwind v4 @theme block.
 *                          Base layer on :root; tier deltas under [data-tier="X"].
 *                          Token refs preserved as var() calls so edits cascade.
 *   tokens.ts            - Typed TS exports preserving the legacy public shape.
 *                          Refs resolved to literal values (no runtime var system).
 *   tailwind.preset.cjs  - Tailwind v3/v4 preset for apps that prefer JS config.
 *   tokens.dart          - Flutter constants for EQ Cards. Refs resolved to literals.
 *
 * Source-of-truth is tokens/. The four artefacts above are *generated* and
 * MUST NOT be hand-edited. CI verifies sources and outputs stay in sync.
 *
 * Usage:  node build.mjs
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = __dirname;
const BASE_DIR  = join(ROOT, 'tokens', 'base');
const TIERS_DIR = join(ROOT, 'tokens', 'tiers');
const TIERS     = ['standard', 'advanced', 'enterprise'];

const HEADER_LINE = '/* THIS FILE IS GENERATED by build.mjs. Do not edit. Edit tokens/*.json and run `npm run build`. */';

// ─────────────────────────────────────────────────────────────────────────────
// 1. Load JSON sources (refs kept as {path} strings)
// ─────────────────────────────────────────────────────────────────────────────

function loadJsonDir(dir) {
  const out = {};
  for (const entry of readdirSync(dir).sort()) {
    if (!entry.endsWith('.json')) continue;
    const raw = JSON.parse(readFileSync(join(dir, entry), 'utf8'));
    delete raw._meta;
    mergeDeep(out, raw);
  }
  return out;
}

function mergeDeep(target, source) {
  for (const [k, v] of Object.entries(source)) {
    if (v && typeof v === 'object' && !Array.isArray(v) && !('value' in v)) {
      target[k] = target[k] ?? {};
      mergeDeep(target[k], v);
    } else {
      target[k] = v;
    }
  }
  return target;
}

const baseUnresolved = loadJsonDir(BASE_DIR);
const tierOverrides = {};
for (const tier of TIERS) {
  tierOverrides[tier] = JSON.parse(readFileSync(join(TIERS_DIR, `${tier}.json`), 'utf8'));
  delete tierOverrides[tier]._meta;
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Reference resolution (for TS / Dart only)
// ─────────────────────────────────────────────────────────────────────────────

const REF_RE = /\{([^}]+)\}/g;

function resolveValue(value, root) {
  if (typeof value !== 'string') return value;
  return value.replace(REF_RE, (whole, path) => {
    const parts = path.split('.');
    let cur = root;
    for (const p of parts) {
      if (cur == null) return whole;
      cur = cur[p];
    }
    return typeof cur === 'string' ? cur : whole;
  });
}

function deepClone(o) { return JSON.parse(JSON.stringify(o)); }

function resolveTree(tree, root = tree) {
  walkTokens(tree, (token) => { token.value = resolveValue(token.value, root); });
}

function walkTokens(tree, fn, path = []) {
  for (const [k, v] of Object.entries(tree)) {
    if (v == null || typeof v !== 'object') continue;
    if ('value' in v) {
      fn(v, [...path, k]);
    } else {
      walkTokens(v, fn, [...path, k]);
    }
  }
}

const baseResolved = deepClone(baseUnresolved);
resolveTree(baseResolved);

// ─────────────────────────────────────────────────────────────────────────────
// 3. Path → CSS var name + display order
// ─────────────────────────────────────────────────────────────────────────────

function cssVarName(path) {
  const p = path;
  if (p[0] === 'color' && p[1] === 'brand') return `--eq-${kebab(p[2])}`;
  if (p[0] === 'color' && p[1] === 'gray')  return `--eq-gray-${p[2]}`;
  if (p[0] === 'color' && p[1] === 'status') return `--eq-${p[2]}-${p[3]}`;
  if (p[0] === 'color' && p[1] === 'accent') return `--eq-${kebab(p[2])}`;
  if (p[0] === 'typography' && p[1] === 'scale')     return `--eq-text-${p[2]}`;
  if (p[0] === 'typography' && p[1] === 'body')      return `--eq-body-${kebab(p[2])}`;
  if (p[0] === 'typography' && p[1] === 'tracking')  return `--eq-tracking-${p[2]}`;
  if (p[0] === 'typography' && p[1] === 'label')     return `--eq-label-${p[2]}`;
  if (p[0] === 'typography' && p[1] === 'fontStack') return `--eq-font-stack`;
  if (p[0] === 'typography' && p[1] === 'weight')    return `--eq-weight-${p[2]}`;
  if (p[0] === 'spacing' && p[1] === 'contentMaxWidth') return `--eq-content-max-width`;
  if (p[0] === 'spacing') return `--eq-space-${p[1]}`;
  if (p[0] === 'radius')  return `--eq-radius-${p[1]}`;
  if (p[0] === 'border' && p[1] === 'inputColor') return `--eq-input-border-color`;
  if (p[0] === 'border')  return `--eq-border-${kebab(p[1])}`;
  if (p[0] === 'shadow')  return `--eq-shadow-${p[1]}`;
  if (p[0] === 'motion' && p[1] === 'duration') return `--eq-duration-${p[2]}`;
  if (p[0] === 'motion' && p[1] === 'ease')     return `--eq-ease`;
  if (p[0] === 'focus'  && p[1] === 'ring')     return `--eq-focus-ring`;
  if (p[0] === 'focus'  && p[1] === 'offset')   return `--eq-focus-offset`;
  if (p[0] === 'tier'   && p[1] === 'accent')   return `--eq-tier-accent`;
  throw new Error(`Unknown token path: ${p.join('.')}`);
}

function kebab(s) { return s.replace(/[A-Z]/g, m => '-' + m.toLowerCase()); }

// Logical section order — matches the v0.1.0 hand-authored layout.
const SECTIONS = [
  { title: 'BRAND COLOURS — use these and nothing else for brand surfaces',           filter: p => p[0] === 'color' && p[1] === 'brand' },
  { title: 'ACCENT — secondary warmth (clay). Brand decoration only (~5%), never status.', filter: p => p[0] === 'color' && p[1] === 'accent' },
  { title: 'NEUTRAL SCALE — Direction D warm-sand surfaces; text greys (400-600) stay neutral', filter: p => p[0] === 'color' && p[1] === 'gray' },
  { title: 'STATUS COLOURS — pass / fail / attention only, never as brand',           filter: p => p[0] === 'color' && p[1] === 'status' },
  { title: 'TIER — per-tenant accent. Defaults to brand.sky; Enterprise overrides.',  filter: p => p[0] === 'tier' },
  { title: 'TYPE — font stack, scale, weights, body, tracking, label',                filter: p => p[0] === 'typography' },
  { title: 'SPACING — 8-pixel grid, with 4 as the half-step',                         filter: p => p[0] === 'spacing' },
  { title: 'RADII — semantic, not numeric',                                           filter: p => p[0] === 'radius' },
  { title: 'BORDERS — single canonical hairline; coloured accents are forbidden',     filter: p => p[0] === 'border' },
  { title: 'SHADOWS — floating UI only. Static cards sit flat with a 1px border.',    filter: p => p[0] === 'shadow' },
  { title: 'MOTION — 150ms default. No bounce.',                                      filter: p => p[0] === 'motion' },
  { title: 'FOCUS RING — required on every focusable input',                          filter: p => p[0] === 'focus' },
];

function flatten(tree) {
  const out = [];
  walkTokens(tree, (token, path) => out.push({ path, value: token.value, comment: token.comment ?? null }));
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. CSS output  →  tokens.css
// ─────────────────────────────────────────────────────────────────────────────

function cssValue(rawValue) {
  // Refs `{a.b.c.value}` become `var(--eq-...)`. Inline (mixed) refs supported.
  return String(rawValue).replace(REF_RE, (_, path) => {
    const parts = path.split('.');
    if (parts[parts.length - 1] === 'value') parts.pop();
    return `var(${cssVarName(parts)})`;
  });
}

function emitCssLine(path, value, comment, indent = '  ') {
  const name = cssVarName(path);
  const c = comment ? ` /* ${comment} */` : '';
  return `${indent}${name}: ${cssValue(value)};${c}`;
}

function buildCss() {
  const baseFlat = flatten(baseUnresolved);
  const out = [];
  out.push(HEADER_LINE);
  out.push(`/* ============================================================================`);
  out.push(` * @eq-solutions/tokens v1.2 — canonical EQ Solutions design tokens`);
  out.push(` *`);
  out.push(` * Single source of truth for colour, type, spacing, radii, shadow, motion.`);
  out.push(` * Base layer applies on :root. Per-tier deltas apply under [data-tier="..."].`);
  out.push(` * Shell sets data-tier on root from the tenant's JWT tier claim.`);
  out.push(` * ========================================================================== */`);
  out.push('');
  out.push(':root {');
  for (const section of SECTIONS) {
    const inSection = baseFlat.filter(t => section.filter(t.path));
    if (inSection.length === 0) continue;
    out.push('');
    out.push(`  /* ── ${section.title} ─────────────────────────────────── */`);
    for (const { path, value, comment } of inSection) {
      out.push(emitCssLine(path, value, comment));
    }
  }
  out.push('}');
  out.push('');

  for (const tier of TIERS) {
    const deltas = flatten(tierOverrides[tier]);
    out.push(`[data-tier="${tier}"] {`);
    if (deltas.length === 0) {
      out.push(`  /* ${tier} inherits the base layer. */`);
    } else {
      for (const { path, value, comment } of deltas) {
        out.push(emitCssLine(path, value, comment));
      }
    }
    out.push('}');
    out.push('');
  }

  out.push('/* ============================================================================');
  out.push(' * TAILWIND v4 @theme — exposes the tokens above as utility classes.');
  out.push(' * Drop this block when consuming from a non-Tailwind app (no-op outside Tailwind).');
  out.push(' * ========================================================================== */');
  out.push('@theme inline {');
  for (const { path } of baseFlat) {
    const themeKey = tailwindThemeKey(path);
    if (themeKey) out.push(`  ${themeKey}: var(${cssVarName(path)});`);
  }
  out.push('  --font-sans: var(--font-jakarta), Arial, sans-serif;');
  out.push('}');
  out.push('');

  // Global accessibility & motion — ships suite-wide from the foundation so every
  // app gets a consistent focus ring + honours reduced-motion without re-declaring.
  // :where() has zero specificity, so components can still override.
  out.push('/* ============================================================================');
  out.push(' * GLOBAL ACCESSIBILITY & MOTION — suite-wide, from the foundation.');
  out.push(' * ========================================================================== */');
  out.push(':where(a, button, input, select, textarea, [tabindex], [role="button"], [role="tab"]):focus-visible {');
  out.push('  outline: 2px solid var(--eq-sky);');
  out.push('  outline-offset: var(--eq-focus-offset, 2px);');
  out.push('  border-radius: var(--eq-radius-chip, 4px);');
  out.push('}');
  out.push('@media (prefers-reduced-motion: reduce) {');
  out.push('  *, *::before, *::after {');
  out.push('    animation-duration: 0.01ms !important;');
  out.push('    animation-iteration-count: 1 !important;');
  out.push('    transition-duration: 0.01ms !important;');
  out.push('    scroll-behavior: auto !important;');
  out.push('  }');
  out.push('}');
  out.push('');

  return out.join('\n');
}

function tailwindThemeKey(path) {
  const p = path;
  if (p[0] === 'color' && p[1] === 'brand')  return `--color-eq-${kebab(p[2])}`;
  if (p[0] === 'color' && p[1] === 'gray')   return `--color-eq-gray-${p[2]}`;
  if (p[0] === 'color' && p[1] === 'status') return `--color-eq-${p[2]}-${p[3]}`;
  if (p[0] === 'color' && p[1] === 'accent') return `--color-eq-${kebab(p[2])}`;
  if (p[0] === 'tier'  && p[1] === 'accent') return `--color-eq-tier-accent`;
  if (p[0] === 'typography' && p[1] === 'scale') return `--text-eq-${p[2]}`;
  if (p[0] === 'radius')  return `--radius-eq-${p[1]}`;
  if (p[0] === 'shadow')  return `--shadow-eq-${p[1]}`;
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. TS output  →  tokens.ts
// ─────────────────────────────────────────────────────────────────────────────

function pxToNumber(v) {
  if (typeof v !== 'string') return v;
  const m = v.match(/^(-?\d+(?:\.\d+)?)px$/);
  return m ? Number(m[1]) : v;
}

function buildTs() {
  const c = baseResolved.color;
  const t = baseResolved.typography;
  const sp = baseResolved.spacing;
  const r = baseResolved.radius;
  const b = baseResolved.border;
  const sh = baseResolved.shadow;
  const m = baseResolved.motion;
  const f = baseResolved.focus;

  return `${HEADER_LINE}
/**
 * @eq-solutions/tokens v1.2 — programmatic access to EQ design tokens.
 *
 * Use this when you need token values inside TypeScript / JavaScript rather
 * than CSS — e.g. inline styles for charts, canvas drawing, generated PDFs,
 * email templates, or feeding a non-CSS rendering layer.
 *
 * Source of truth is tokens/*.json. Regenerate via \`npm run build\`.
 */

export const colours = {
  brand: {
    sky:     '${c.brand.sky.value}',
    deep:    '${c.brand.deep.value}',
    skyDeep: '${c.brand.skyDeep.value}',
    ice:     '${c.brand.ice.value}',
    ink:     '${c.brand.ink.value}',
    grey:    '${c.brand.grey.value}',
    white:   '${c.brand.white.value}',
    amber:     '${c.brand.amber.value}',
    amberDeep: '${c.brand.amberDeep.value}',
    slate:     '${c.brand.slate.value}',
    live:      '${c.brand.live.value}',
  },
  accent: {
    clay:     '${c.accent.clay.value}',
    clayDeep: '${c.accent.clayDeep.value}',
    clayBg:   '${c.accent.clayBg.value}',
  },
  gray: {
    50:  '${c.gray['50'].value}',
    100: '${c.gray['100'].value}',
    200: '${c.gray['200'].value}',
    300: '${c.gray['300'].value}',
    400: '${c.gray['400'].value}',
    500: '${c.gray['500'].value}',
    600: '${c.gray['600'].value}',
  },
  status: {
    successBg:   '${c.status.success.bg.value}',
    successText: '${c.status.success.text.value}',
    warningBg:   '${c.status.warning.bg.value}',
    warningText: '${c.status.warning.text.value}',
    errorBg:     '${c.status.error.bg.value}',
    errorText:   '${c.status.error.text.value}',
  },
} as const;

export const typography = {
  fontStack: \`${t.fontStack.value}\`,
  scale: {
    xs:   ${pxToNumber(t.scale.xs.value)},
    sm:   ${pxToNumber(t.scale.sm.value)},
    base: ${pxToNumber(t.scale.base.value)},
    md:   ${pxToNumber(t.scale.md.value)},
    lg:   ${pxToNumber(t.scale.lg.value)},
    xl:   ${pxToNumber(t.scale.xl.value)},
    '2xl': ${pxToNumber(t.scale['2xl'].value)},
    '3xl': ${pxToNumber(t.scale['3xl'].value)},
    '4xl': ${pxToNumber(t.scale['4xl'].value)},
  },
  weights: {
    regular: ${t.weight.regular.value},
    medium:  ${t.weight.medium.value},
    semi:    ${t.weight.semi.value},
    bold:    ${t.weight.bold.value},
    black:   ${t.weight.black.value},
  },
  body: {
    lineHeight: ${t.body.lineHeight.value},
    weight: ${t.body.weight.value},
  },
  tracking: {
    tight:   '${t.tracking.tight.value}',
    tighter: '${t.tracking.tighter.value}',
    label:   '${t.tracking.label.value}',
  },
  label: {
    size: ${pxToNumber(t.label.size.value)},
    weight: ${t.label.weight.value},
  },
} as const;

export const spacing = {
  1: ${pxToNumber(sp['1'].value)},
  2: ${pxToNumber(sp['2'].value)},
  3: ${pxToNumber(sp['3'].value)},
  4: ${pxToNumber(sp['4'].value)},
  5: ${pxToNumber(sp['5'].value)},
  6: ${pxToNumber(sp['6'].value)},
  8: ${pxToNumber(sp['8'].value)},
  10: ${pxToNumber(sp['10'].value)},
  12: ${pxToNumber(sp['12'].value)},
  16: ${pxToNumber(sp['16'].value)},
  contentMaxWidth: ${pxToNumber(sp.contentMaxWidth.value)},
} as const;

export const radii = {
  chip:  ${pxToNumber(r.chip.value)},
  input: ${pxToNumber(r.input.value)},
  card:  ${pxToNumber(r.card.value)},
  shell: ${pxToNumber(r.shell.value)},
  pill:  ${pxToNumber(r.pill.value)},
} as const;

export const borders = {
  width: ${pxToNumber(b.width.value)},
  color: '${b.color.value}',
  inputColor: '${b.inputColor.value}',
} as const;

export const shadows = {
  sm: '${sh.sm.value}',
  lg: '${sh.lg.value}',
  elevated: '${sh.elevated.value}',
} as const;

export const motion = {
  durationDefault: ${parseInt(m.duration.default.value, 10)},
  durationDrawer:  ${parseInt(m.duration.drawer.value, 10)},
  durationSpinner: ${parseInt(m.duration.spinner.value, 10)},
  ease: '${m.ease.value}',
} as const;

export const focus = {
  ring: '${f.ring.value}',
  offset: ${pxToNumber(f.offset.value)},
} as const;

export const tier = {
  accent: '${baseResolved.tier.accent.value}',
} as const;

/**
 * Convenience aggregate. Prefer named imports
 * (\`import { colours } from '@eq-solutions/tokens'\`) over destructuring this default.
 */
export const tokens = {
  colours,
  typography,
  spacing,
  radii,
  borders,
  shadows,
  motion,
  focus,
  tier,
} as const;

export default tokens;
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. Tailwind preset  →  tailwind.preset.cjs
// ─────────────────────────────────────────────────────────────────────────────

function buildTailwindPreset() {
  return `${HEADER_LINE}
/**
 * @eq-solutions/tokens v1.2 — Tailwind preset (v3 + v4 compatible).
 *
 * For Tailwind v4 the inline @theme block in tokens.css is the preferred path;
 * this preset is for v3 apps or v4 apps that prefer JS config.
 *
 * Usage:
 *   // tailwind.config.cjs
 *   module.exports = {
 *     presets: [require('@eq-solutions/tokens/tailwind.preset.cjs')],
 *     content: [...],
 *   };
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        'eq-sky':      'var(--eq-sky)',
        'eq-deep':     'var(--eq-deep)',
        'eq-sky-deep': 'var(--eq-sky-deep)',
        'eq-ice':      'var(--eq-ice)',
        'eq-ink':      'var(--eq-ink)',
        'eq-grey':     'var(--eq-grey)',
        'eq-white':    'var(--eq-white)',
        'eq-amber':      'var(--eq-amber)',
        'eq-amber-deep': 'var(--eq-amber-deep)',
        'eq-slate':      'var(--eq-slate)',
        'eq-live':       'var(--eq-live)',
        'eq-clay':      'var(--eq-clay)',
        'eq-clay-deep': 'var(--eq-clay-deep)',
        'eq-clay-bg':   'var(--eq-clay-bg)',
        'eq-gray': {
          50:  'var(--eq-gray-50)',
          100: 'var(--eq-gray-100)',
          200: 'var(--eq-gray-200)',
          300: 'var(--eq-gray-300)',
          400: 'var(--eq-gray-400)',
          500: 'var(--eq-gray-500)',
          600: 'var(--eq-gray-600)',
        },
        'eq-success-bg':   'var(--eq-success-bg)',
        'eq-success-text': 'var(--eq-success-text)',
        'eq-warning-bg':   'var(--eq-warning-bg)',
        'eq-warning-text': 'var(--eq-warning-text)',
        'eq-error-bg':     'var(--eq-error-bg)',
        'eq-error-text':   'var(--eq-error-text)',
        'eq-tier-accent':  'var(--eq-tier-accent)',
      },
      borderRadius: {
        'eq-chip':  'var(--eq-radius-chip)',
        'eq-input': 'var(--eq-radius-input)',
        'eq-card':  'var(--eq-radius-card)',
        'eq-shell': 'var(--eq-radius-shell)',
        'eq-pill':  'var(--eq-radius-pill)',
      },
      boxShadow: {
        'eq-sm':       'var(--eq-shadow-sm)',
        'eq-lg':       'var(--eq-shadow-lg)',
        'eq-elevated': 'var(--eq-shadow-elevated)',
      },
      fontSize: {
        'eq-xs':   'var(--eq-text-xs)',
        'eq-sm':   'var(--eq-text-sm)',
        'eq-base': 'var(--eq-text-base)',
        'eq-md':   'var(--eq-text-md)',
        'eq-lg':   'var(--eq-text-lg)',
        'eq-xl':   'var(--eq-text-xl)',
        'eq-2xl':  'var(--eq-text-2xl)',
        'eq-3xl':  'var(--eq-text-3xl)',
        'eq-4xl':  'var(--eq-text-4xl)',
      },
      fontFamily: {
        sans: ['var(--font-jakarta)', 'Arial', 'sans-serif'],
      },
      spacing: {
        'eq-1':  'var(--eq-space-1)',
        'eq-2':  'var(--eq-space-2)',
        'eq-3':  'var(--eq-space-3)',
        'eq-4':  'var(--eq-space-4)',
        'eq-5':  'var(--eq-space-5)',
        'eq-6':  'var(--eq-space-6)',
        'eq-8':  'var(--eq-space-8)',
        'eq-10': 'var(--eq-space-10)',
        'eq-12': 'var(--eq-space-12)',
        'eq-16': 'var(--eq-space-16)',
      },
      transitionDuration: {
        'eq-default': 'var(--eq-duration-default)',
        'eq-drawer':  'var(--eq-duration-drawer)',
        'eq-spinner': 'var(--eq-duration-spinner)',
      },
      transitionTimingFunction: {
        'eq': 'var(--eq-ease)',
      },
    },
  },
};
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. Dart output  →  tokens.dart  (Flutter consumer - EQ Cards)
// ─────────────────────────────────────────────────────────────────────────────

function hexToFlutterColor(hex) {
  const h = hex.replace('#', '').toUpperCase();
  if (h.length !== 6) throw new Error(`Bad hex for Flutter color: ${hex}`);
  return `Color(0xFF${h})`;
}

function buildDart() {
  const c = baseResolved.color;
  const sp = baseResolved.spacing;
  const r = baseResolved.radius;
  const t = baseResolved.typography;
  return `${HEADER_LINE}
// @eq-solutions/tokens v1.2 — Flutter constants for EQ Cards.
//
// Source of truth is tokens/*.json. Regenerate via \`npm run build\`.

import 'package:flutter/material.dart';

class EqColors {
  EqColors._();

  // Brand
  static const Color sky     = ${hexToFlutterColor(c.brand.sky.value)};
  static const Color deep    = ${hexToFlutterColor(c.brand.deep.value)};
  static const Color skyDeep = ${hexToFlutterColor(c.brand.skyDeep.value)};
  static const Color ice     = ${hexToFlutterColor(c.brand.ice.value)};
  static const Color ink     = ${hexToFlutterColor(c.brand.ink.value)};
  static const Color grey    = ${hexToFlutterColor(c.brand.grey.value)};
  static const Color white   = ${hexToFlutterColor(c.brand.white.value)};
  static const Color amber     = ${hexToFlutterColor(c.brand.amber.value)};
  static const Color amberDeep = ${hexToFlutterColor(c.brand.amberDeep.value)};
  static const Color slate     = ${hexToFlutterColor(c.brand.slate.value)};
  static const Color live      = ${hexToFlutterColor(c.brand.live.value)};

  // Accent (Direction D)
  static const Color clay     = ${hexToFlutterColor(c.accent.clay.value)};
  static const Color clayDeep = ${hexToFlutterColor(c.accent.clayDeep.value)};
  static const Color clayBg   = ${hexToFlutterColor(c.accent.clayBg.value)};

  // Neutral scale
  static const Color gray50  = ${hexToFlutterColor(c.gray['50'].value)};
  static const Color gray100 = ${hexToFlutterColor(c.gray['100'].value)};
  static const Color gray200 = ${hexToFlutterColor(c.gray['200'].value)};
  static const Color gray300 = ${hexToFlutterColor(c.gray['300'].value)};
  static const Color gray400 = ${hexToFlutterColor(c.gray['400'].value)};
  static const Color gray500 = ${hexToFlutterColor(c.gray['500'].value)};
  static const Color gray600 = ${hexToFlutterColor(c.gray['600'].value)};

  // Status
  static const Color successBg   = ${hexToFlutterColor(c.status.success.bg.value)};
  static const Color successText = ${hexToFlutterColor(c.status.success.text.value)};
  static const Color warningBg   = ${hexToFlutterColor(c.status.warning.bg.value)};
  static const Color warningText = ${hexToFlutterColor(c.status.warning.text.value)};
  static const Color errorBg     = ${hexToFlutterColor(c.status.error.bg.value)};
  static const Color errorText   = ${hexToFlutterColor(c.status.error.text.value)};
}

class EqSpacing {
  EqSpacing._();
  static const double s1  = ${pxToNumber(sp['1'].value)};
  static const double s2  = ${pxToNumber(sp['2'].value)};
  static const double s3  = ${pxToNumber(sp['3'].value)};
  static const double s4  = ${pxToNumber(sp['4'].value)};
  static const double s5  = ${pxToNumber(sp['5'].value)};
  static const double s6  = ${pxToNumber(sp['6'].value)};
  static const double s8  = ${pxToNumber(sp['8'].value)};
  static const double s10 = ${pxToNumber(sp['10'].value)};
  static const double s12 = ${pxToNumber(sp['12'].value)};
  static const double s16 = ${pxToNumber(sp['16'].value)};
}

class EqRadius {
  EqRadius._();
  static const double chip  = ${pxToNumber(r.chip.value)};
  static const double input = ${pxToNumber(r.input.value)};
  static const double card  = ${pxToNumber(r.card.value)};
  static const double shell = ${pxToNumber(r.shell.value)};
  static const double pill  = ${pxToNumber(r.pill.value)};
}

class EqTypography {
  EqTypography._();
  static const String fontFamily = 'PlusJakartaSans';
  static const double xs   = ${pxToNumber(t.scale.xs.value)};
  static const double sm   = ${pxToNumber(t.scale.sm.value)};
  static const double base = ${pxToNumber(t.scale.base.value)};
  static const double md   = ${pxToNumber(t.scale.md.value)};
  static const double lg   = ${pxToNumber(t.scale.lg.value)};
  static const double xl   = ${pxToNumber(t.scale.xl.value)};
  static const double xl2  = ${pxToNumber(t.scale['2xl'].value)};
  static const double xl3  = ${pxToNumber(t.scale['3xl'].value)};
  static const double xl4  = ${pxToNumber(t.scale['4xl'].value)};

  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium  = FontWeight.w500;
  static const FontWeight semi    = FontWeight.w600;
  static const FontWeight bold    = FontWeight.w700;
  static const FontWeight black   = FontWeight.w800;
}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// 8. Write outputs
// ─────────────────────────────────────────────────────────────────────────────

function emit(filename, contents) {
  const path = join(ROOT, filename);
  writeFileSync(path, contents);
  const bytes = Buffer.byteLength(contents, 'utf8');
  console.log(`  ${filename.padEnd(22)}${bytes.toLocaleString().padStart(8)} bytes`);
}

console.log('Building @eq-solutions/tokens v1.2 ...');
emit('tokens.css',          buildCss());
emit('tokens.ts',           buildTs());
emit('tailwind.preset.cjs', buildTailwindPreset());
emit('tokens.dart',         buildDart());
console.log('Done.');
