/* THIS FILE IS GENERATED by build.mjs. Do not edit. Edit tokens/*.json and run `npm run build`. */
/**
 * @eq-solutions/tokens v1.2 — Tailwind preset (v3 + v4 compatible).
 *
 * For Tailwind v4 the inline @theme block in tokens.css is the preferred path;
 * this preset is for v3 apps or v4 apps that prefer JS config.
 *
 * Usage:
 *   // tailwind.config.cjs
 *   module.exports = {
 *     presets: [require('@eq-solutions/tokens/tailwind.preset.cjs')],
 *     content: [...],
 *   };
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        'eq-sky':      'var(--eq-sky)',
        'eq-deep':     'var(--eq-deep)',
        'eq-sky-deep': 'var(--eq-sky-deep)',
        'eq-ice':      'var(--eq-ice)',
        'eq-ink':      'var(--eq-ink)',
        'eq-grey':     'var(--eq-grey)',
        'eq-white':    'var(--eq-white)',
        'eq-amber':      'var(--eq-amber)',
        'eq-amber-deep': 'var(--eq-amber-deep)',
        'eq-slate':      'var(--eq-slate)',
        'eq-live':       'var(--eq-live)',
        'eq-clay':      'var(--eq-clay)',
        'eq-clay-deep': 'var(--eq-clay-deep)',
        'eq-clay-bg':   'var(--eq-clay-bg)',
        'eq-gray': {
          50:  'var(--eq-gray-50)',
          100: 'var(--eq-gray-100)',
          200: 'var(--eq-gray-200)',
          300: 'var(--eq-gray-300)',
          400: 'var(--eq-gray-400)',
          500: 'var(--eq-gray-500)',
          600: 'var(--eq-gray-600)',
        },
        'eq-success-bg':   'var(--eq-success-bg)',
        'eq-success-text': 'var(--eq-success-text)',
        'eq-warning-bg':   'var(--eq-warning-bg)',
        'eq-warning-text': 'var(--eq-warning-text)',
        'eq-error-bg':     'var(--eq-error-bg)',
        'eq-error-text':   'var(--eq-error-text)',
        'eq-tier-accent':  'var(--eq-tier-accent)',
      },
      borderRadius: {
        'eq-chip':  'var(--eq-radius-chip)',
        'eq-input': 'var(--eq-radius-input)',
        'eq-card':  'var(--eq-radius-card)',
        'eq-shell': 'var(--eq-radius-shell)',
        'eq-pill':  'var(--eq-radius-pill)',
      },
      boxShadow: {
        'eq-sm':       'var(--eq-shadow-sm)',
        'eq-lg':       'var(--eq-shadow-lg)',
        'eq-elevated': 'var(--eq-shadow-elevated)',
      },
      fontSize: {
        'eq-xs':   'var(--eq-text-xs)',
        'eq-sm':   'var(--eq-text-sm)',
        'eq-base': 'var(--eq-text-base)',
        'eq-md':   'var(--eq-text-md)',
        'eq-lg':   'var(--eq-text-lg)',
        'eq-xl':   'var(--eq-text-xl)',
        'eq-2xl':  'var(--eq-text-2xl)',
        'eq-3xl':  'var(--eq-text-3xl)',
        'eq-4xl':  'var(--eq-text-4xl)',
      },
      fontFamily: {
        sans: ['var(--font-jakarta)', 'Arial', 'sans-serif'],
      },
      spacing: {
        'eq-1':  'var(--eq-space-1)',
        'eq-2':  'var(--eq-space-2)',
        'eq-3':  'var(--eq-space-3)',
        'eq-4':  'var(--eq-space-4)',
        'eq-5':  'var(--eq-space-5)',
        'eq-6':  'var(--eq-space-6)',
        'eq-8':  'var(--eq-space-8)',
        'eq-10': 'var(--eq-space-10)',
        'eq-12': 'var(--eq-space-12)',
        'eq-16': 'var(--eq-space-16)',
      },
      transitionDuration: {
        'eq-default': 'var(--eq-duration-default)',
        'eq-drawer':  'var(--eq-duration-drawer)',
        'eq-spinner': 'var(--eq-duration-spinner)',
      },
      transitionTimingFunction: {
        'eq': 'var(--eq-ease)',
      },
    },
  },
};
