/* THIS FILE IS GENERATED by build.mjs. Do not edit. Edit tokens/*.json and run `npm run build`. */
// @eq-solutions/tokens v1.3 — Flutter constants for EQ Cards.
//
// Source of truth is tokens/*.json. Regenerate via `npm run build`.

import 'package:flutter/material.dart';

class EqColors {
  EqColors._();

  // Brand
  static const Color sky     = Color(0xFF3DA8D8);
  static const Color deep    = Color(0xFF2986B4);
  static const Color skyDeep = Color(0xFF2986B4);
  static const Color ice     = Color(0xFFEAF5FB);
  static const Color ink     = Color(0xFF1A1A2E);
  static const Color grey    = Color(0xFF666666);
  static const Color white   = Color(0xFFFFFFFF);
  static const Color amber     = Color(0xFFF59E0B);
  static const Color amberDeep = Color(0xFFB45309);
  static const Color slate     = Color(0xFF94A3B8);
  static const Color live      = Color(0xFF38BDF8);

  // Accent (Direction D)
  static const Color clay     = Color(0xFFA8572B);
  static const Color clayDeep = Color(0xFF8A4521);
  static const Color clayBg   = Color(0xFFFBF1E9);

  // Neutral scale
  static const Color gray50  = Color(0xFFF6F3EE);
  static const Color gray100 = Color(0xFFEFEAE1);
  static const Color gray200 = Color(0xFFE4DDD2);
  static const Color gray300 = Color(0xFFD4CCBE);
  static const Color gray400 = Color(0xFF9CA3AF);
  static const Color gray500 = Color(0xFF6B7280);
  static const Color gray600 = Color(0xFF4B5563);

  // Status
  static const Color successBg   = Color(0xFFF0FDF4);
  static const Color successText = Color(0xFF15803D);
  static const Color warningBg   = Color(0xFFFFFBEB);
  static const Color warningText = Color(0xFFB45309);
  static const Color errorBg     = Color(0xFFFEF2F2);
  static const Color errorText   = Color(0xFFB91C1C);
}

class EqSpacing {
  EqSpacing._();
  static const double s1  = 4;
  static const double s2  = 8;
  static const double s3  = 12;
  static const double s4  = 16;
  static const double s5  = 20;
  static const double s6  = 24;
  static const double s8  = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
}

class EqRadius {
  EqRadius._();
  static const double chip  = 4;
  static const double input = 6;
  static const double card  = 8;
  static const double shell = 12;
  static const double pill  = 9999;
}

class EqTypography {
  EqTypography._();
  static const String fontFamily = 'PlusJakartaSans';
  static const double xs   = 11;
  static const double sm   = 12;
  static const double base = 14;
  static const double md   = 15;
  static const double lg   = 18;
  static const double xl   = 22;
  static const double xl2  = 28;
  static const double xl3  = 36;
  static const double xl4  = 48;

  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium  = FontWeight.w500;
  static const FontWeight semi    = FontWeight.w600;
  static const FontWeight bold    = FontWeight.w700;
  static const FontWeight black   = FontWeight.w800;
}
